import forms from "@tailwindcss/forms";
import type { Config } from "tailwindcss";

const tailwindConfig: Config = {
	content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
	darkMode: "class",
	theme: {
		extend: {
			colors: {
				"on-background": "#1b1c18",
				"on-tertiary-fixed-variant": "#5d4200",
				"outline-variant": "#c4c8b9",
				"surface-variant": "#e4e2dc",
				"surface-tint": "#536252",
				"secondary-fixed-dim": "#b0d18d",
				"on-surface": "#1b1c18",
				"on-primary": "#ffffff",
				"error-container": "#ffdad6",
				"surface-container": "#f0eee8",
				"primary-container": "#9aaa97",
				surface: "#fbf9f3",
				"on-tertiary": "#ffffff",
				"on-tertiary-container": "#4f3700",
				"inverse-on-surface": "#f3f1eb",
				"inverse-surface": "#30312d",
				"on-secondary-fixed": "#0e2000",
				"inverse-primary": "#bbcbb8",
				"on-secondary-container": "#4e6b32",
				background: "#fbf9f3",
				"surface-container-highest": "#e4e2dc",
				"tertiary-fixed-dim": "#eec068",
				secondary: "#4a662e",
				"on-secondary": "#ffffff",
				"on-secondary-fixed-variant": "#334e18",
				"secondary-fixed": "#cbeda6",
				"surface-bright": "#fbf9f3",
				"surface-container-lowest": "#ffffff",
				tertiary: "#7b5804",
				"on-primary-fixed": "#111f12",
				"primary-fixed": "#d7e7d3",
				outline: "#74796c",
				"surface-container-low": "#f6f3ed",
				"secondary-container": "#c8eba4",
				"surface-container-high": "#eae8e2",
				"on-primary-container": "#303e30",
				"tertiary-container": "#ca9f4b",
				"surface-dim": "#dcdad4",
				"on-surface-variant": "#44483d",
				error: "#ba1a1a",
				"primary-fixed-dim": "#bbcbb8",
				"on-primary-fixed-variant": "#3c4a3c",
				"on-error": "#ffffff",
				"tertiary-fixed": "#ffdea6",
				"on-tertiary-fixed": "#271900",
				"on-error-container": "#93000a",
				primary: "#536252",
			},
			fontFamily: {
				headline: ["Inter"],
				body: ["Inter"],
				label: ["Inter"],
			},
			borderRadius: { DEFAULT: "8px", lg: "12px", xl: "16px", full: "9999px" },
		},
	},
	plugins: [forms],
};

export default tailwindConfig;
